
- hosts: WLB1
  remote_user: root
  roles:
   - nginx
   - web_balancer 

- hosts: web1
  remote_user: root
  roles:
   - nginx
   - git
   - php-fpm
   - web

- hosts: percona
  remote_user: root
  roles:
   - percona_cluster
   
- hosts: DLB
  remote_user: root
  roles:
   - proxysql2   
   
- hosts: percona_rez
  remote_user: root
  roles:
   - percona_rez
   - proxysql2_rez


