
- hosts: WLB
  remote_user: root
  roles:
   #- nginx
   #- web_balancer 

- hosts: web
  remote_user: root
  roles:
   - backup
   #- nginx
   #- git
   #- php-fpm
   #- web

- hosts: percona
  remote_user: root
  roles:
   #- percona_cluster
   - backup

- hosts: DLB
  remote_user: root
  roles:
   - proxysql2   
   
- hosts: percona_rez
  remote_user: root
  roles:
   #- percona_rez
   #- proxysql2_rez


