mysql_root_password: 11111111
mysql_repo_url: https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
percona_repo_url: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
percona_ver: 80

proxysql_user: proxysql_user
proxysql_pass: 1asd.asd!SAVE

mysql_app_user: web_db2
mysql_app_pass: password_for_web_db2

router_id: '{{ inventory_hostname }}'
virtual_ip: 192.168.123.1/24
auth_type: PASS
auth_pass: 232323
virtual_router_id: 33
vrrp_interface: eth0