  schema-registry:
    container_name: schema-registry
    hostname: schema-registry
    image: 'confluentinc/cp-schema-registry:3.1.1'
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=10.0.9.44:2181,10.0.9.45:2181,10.0.9.50:2181
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
    ports:
      - "8081:8081"
 
